### ISSUE TITLE
Can't run this program

### ISSUE THREAD

**Issue by lanjin1997** [George730/E-ResGAT#1]
First, the file address identified by the code is wrong, and secondly, after the modification is completed, the corresponding file cannot be read. Please answer

**Comment by hebo-space** [comment]
Run the prepare file in datasets to regenerate the processed datasets files, the problem could be sovled.

**Comment by furycurry** [comment]
were you able to solve the issue @lanjin1997 ?
(if so, can you let me know how to run the prepare file in dataset?)

**Comment by hebo-space** [comment]
you can use notebook to open the .ipynb file, and new a according .ipynb file and run it with the according datasets.
PS:&nbsp;If you can speak Chinese, you can send me E-mails with Chinese




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "George730/E-ResGAT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月23日(星期三) 中午1:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [George730/E-ResGAT] Can't run this program (Issue #1)





 
were you able to solve the issue @lanjin1997 ?
 (if so, can you let me know how to run the prepare file in dataset?)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hebo-space** [comment]
The Notebook here is a tool, jupyter Notebook，which can run python files





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "George730/E-ResGAT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月23日(星期三) 中午1:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [George730/E-ResGAT] Can't run this program (Issue #1)





 
were you able to solve the issue @lanjin1997 ?
 (if so, can you let me know how to run the prepare file in dataset?)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by furycurry** [comment]
> you can use notebook to open the .ipynb file, and new a according .ipynb file and run it with the according datasets. PS:&nbsp;If you can speak Chinese, you can send me E-mails with Chinese
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "George730/E-ResGAT" ***@***.***&gt;; 发送时间:&nbsp;2022年2月23日(星期三) 中午1:16 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [George730/E-ResGAT] Can't run this program (Issue #1) were you able to solve the issue @lanjin1997 ? (if so, can you let me know how to run the prepare file in dataset?) — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

Can't seem to get around the` **FileNotFoundError**`

![image](https://user-images.githubusercontent.com/58500422/155457273-05dfdf39-fa32-41e2-bd92-d7b68437ad2e.png)

**Comment by George730** [comment]
> > you can use notebook to open the .ipynb file, and new a according .ipynb file and run it with the according datasets. PS: If you can speak Chinese, you can send me E-mails with Chinese
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "George730/E-ResGAT" _**@**_._**>; 发送时间: 2022年2月23日(星期三) 中午1:16 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [George730/E-ResGAT] Can't run this program (Issue #1) were you able to solve the issue @lanjin1997 ? (if so, can you let me know how to run the prepare file in dataset?) — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> Can't seem to get around the` **FileNotFoundError**`
> 
> ![image](https://user-images.githubusercontent.com/58500422/155457273-05dfdf39-fa32-41e2-bd92-d7b68437ad2e.png)

The file named 'UNSW-NB15_test.npy' contains the indexes of test samples. You can use _train_test_split_ or other split methods to create such file. Test the model on this test set, get the embedding and finally visualize. I'll upload a brief description of the visualization this week. Thanks for asking!

**Comment by furycurry** [comment]
While running fit_model.py on console, I have encountered `FileNotFoundError: [Errno 2] No such file or directory: 'datasets/Darknetedge_feat_scaled.npy'`. Went through the **datasets** folder and there were no such files. I think the code was supposed to be directed to this location `datasets/Darknet/edge_feat_scaled.npy`

![image](https://user-images.githubusercontent.com/58500422/155654820-e5a4436a-e5c4-4c05-b4ff-770e8b0fd4fa.png)

**Comment by hebo-space** [comment]
I just run the main code, but not run visualization file yet, sorry. 1031650335 ***@***.*** 签名由 网易邮箱大师 定制 On 02/24/2022 23:51, Liyan Chang wrote: you can use notebook to open the .ipynb file, and new a according .ipynb file and run it with the according datasets. PS: If you can speak Chinese, you can send me E-mails with Chinese … ------------------ 原始邮件 ------------------ 发件人: "George730/E-ResGAT" @.>; 发送时间: 2022年2月23日(星期三) 中午1:16 _@**._>; ***@***.***@._>; 主题: Re: [George730/E-ResGAT] Can't run this program (Issue #1) were you able to solve the issue @lanjin1997 ? (if so, can you let me know how to run the prepare file in dataset?) — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: _@_.*> Can't seem to get around the **FileNotFoundError** The file named 'UNSW-NB15_test.npy' contains the indexes of test samples. You can use train_test_split or other split methods to create such file. Test the model on this test set, get the embedding and finally visualize. I'll upload a brief description of the visualization this week. Thanks for asking! — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by hebo-space** [comment]
After run the according prepare file, the file need to be renamed like Darknetedge_scaled. npy, the datasets name need to be added 1031650335 ***@***.*** 签名由 网易邮箱大师 定制 On 02/25/2022 21:21, ***@***.*** wrote: I just run the main code, but not run visualization file yet, sorry. 1031650335 ***@***.*** 签名由 网易邮箱大师 定制 On 02/24/2022 23:51, Liyan Chang wrote: you can use notebook to open the .ipynb file, and new a according .ipynb file and run it with the according datasets. PS: If you can speak Chinese, you can send me E-mails with Chinese … ------------------ 原始邮件 ------------------ 发件人: "George730/E-ResGAT" @.>; 发送时间: 2022年2月23日(星期三) 中午1:16 _@**._>; ***@***.***@._>; 主题: Re: [George730/E-ResGAT] Can't run this program (Issue #1) were you able to solve the issue @lanjin1997 ? (if so, can you let me know how to run the prepare file in dataset?) — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: _@_.*> Can't seem to get around the **FileNotFoundError** The file named 'UNSW-NB15_test.npy' contains the indexes of test samples. You can use train_test_split or other split methods to create such file. Test the model on this test set, get the embedding and finally visualize. I'll upload a brief description of the visualization this week. Thanks for asking! — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by ylic204** [comment]
hello, guys,
Have you solved this problem yet? I'm having this problem too.
When I try to run the program, `fit_model.py​`, the program prompts an error, `datasets/UNSW-NB15edge_feat_scaled.npy​ could not be found`, so I changed the path and the program reports the following error：

```
path: datasets/UNSW-NB15/
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 460, in load
return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "fit_model.py", line 180, in
fit(args)
File "fit_model.py", line 40, in fit
edge_feat, label, adj, adj_lists, config = load_gat(path, device, binary)
File "/content/gdrive/MyDrive/Colab Notebooks/E-ResGAT-master/loader.py", line 58, in load_gat
edge_feat = np.load(path + "edge_feat_scaled.npy", allow_pickle=True)
File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 463, in load
"Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file 'datasets/UNSW-NB15/edge_feat_scaled.npy' as a pickle
```
So, I checked the `edge_feat_scaled.npy` file, as shown below:
```
version https://git-lfs.github.com/spec/v1
oid sha256:2e0e61b7188919*******0ed417ad94a39d77143e5d9ca1d
size 240800472
```
And all the dataset `edge_feat_scaled.npy` is similar. So I tried to download it using git lfs, but it's still the same after downloading. How can I solve this problem? Also, the authors get edge_feat_scaled.npy via UNSW_prepare.ipynb.
`unsw = pd.read_csv(UNSW-NB15_1.csv, header=None)`.
But the author did not provide the file. So I downloaded the NF-UNSW-NB15 dataset from the web, but the result after loading is different from the original UNSW_prepare.ipynb after running, e.g. `len(unsw) = 700001`, while the downloaded NF-UNSW-NB15 has `len(unsw) = 1623119`.

**Comment by Avancez** [comment]
> While running fit_model.py on console, I have encountered `FileNotFoundError: [Errno 2] No such file or directory: 'datasets/Darknetedge_feat_scaled.npy'`. Went through the **datasets** folder and there were no such files. I think the code was supposed to be directed to this location `datasets/Darknet/edge_feat_scaled.npy`
> 
> ![image](https://user-images.githubusercontent.com/58500422/155654820-e5a4436a-e5c4-4c05-b4ff-770e8b0fd4fa.png)

Is your problem solved?

**Comment by George730** [comment]
> > While running fit_model.py on console, I have encountered `FileNotFoundError: [Errno 2] No such file or directory: 'datasets/Darknetedge_feat_scaled.npy'`. Went through the **datasets** folder and there were no such files. I think the code was supposed to be directed to this location `datasets/Darknet/edge_feat_scaled.npy`
> > ![image](https://user-images.githubusercontent.com/58500422/155654820-e5a4436a-e5c4-4c05-b4ff-770e8b0fd4fa.png)
> 
> Is your problem solved?

There is a slash missing. It should be 'datasets/Darknet/edge_feat_scaled.npy'.

**Comment by Fabiabn** [comment]
你好 可视化的npy文件 怎么获取呢

**Comment by Fabiabn** [comment]
> > you can use notebook to open the .ipynb file, and new a according .ipynb file and run it with the according datasets. PS: If you can speak Chinese, you can send me E-mails with Chinese
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "George730/E-ResGAT" _**@**_._**>; 发送时间: 2022年2月23日(星期三) 中午1:16 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [George730/E-ResGAT] Can't run this program (Issue #1) were you able to solve the issue @lanjin1997 ? (if so, can you let me know how to run the prepare file in dataset?) — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> Can't seem to get around the` **FileNotFoundError**`
> 
> ![image](https://user-images.githubusercontent.com/58500422/155457273-05dfdf39-fa32-41e2-bd92-d7b68437ad2e.png)

Hello  How to run the visualization.ipynb

**Comment by lhr42** [comment]
> > > you can use notebook to open the .ipynb file, and new a according .ipynb file and run it with the according datasets. PS: If you can speak Chinese, you can send me E-mails with Chinese
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "George730/E-ResGAT" _**@**_._**>; 发送时间: 2022年2月23日(星期三) 中午1:16 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [George730/E-ResGAT] Can't run this program (Issue #1) were you able to solve the issue @lanjin1997 ? (if so, can you let me know how to run the prepare file in dataset?) — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > Can't seem to get around the` **FileNotFoundError**`
> > ![image](https://user-images.githubusercontent.com/58500422/155457273-05dfdf39-fa32-41e2-bd92-d7b68437ad2e.png)
> 
> The file named 'UNSW-NB15_test.npy' contains the indexes of test samples. You can use _train_test_split_ or other split methods to create such file. Test the model on this test set, get the embedding and finally visualize. I'll upload a brief description of the visualization this week. Thanks for asking!

Hello, I wonder where can I find this description of the visualization, thanks!
