### ISSUE TITLE
Expected floating point type for target with class probabilities, got Long

### ISSUE THREAD

**Issue by heerlu** [George730/E-ResGAT#5]
Hello, I encountered the following problem when running the code. How should I solve it?

....
batch: 179 loss_train: 0.0063 acc_train: 0.9980 time: 1.9977s
batch: 180 loss_train: 0.0113 acc_train: 0.9943 time: 2.0366s
Traceback (most recent call last):
  File "fit_model.py", line 180, in <module>
    fit(args)
  File "fit_model.py", line 112, in fit
    acc_val, loss_val, val_output = predict_(alg, model, label, loss_fn, val)
  File "fit_model.py", line 142, in predict_
    batch_loss = loss_fn(batch_output, label[batch_edges])
  File "/home/cetc54-5/anaconda3/envs/torchIDS/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cetc54-5/anaconda3/envs/torchIDS/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 1152, in forward
    label_smoothing=self.label_smoothing)
  File "/home/cetc54-5/anaconda3/envs/torchIDS/lib/python3.6/site-packages/torch/nn/functional.py", line 2846, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: Expected floating point type for target with class probabilities, got Long

**Comment by Aleigege** [comment]
Hello, have you solved it yet? Can you share that?

**Comment by junjiunian** [comment]
Hello, have you solved it?@Aleigege

**Comment by Aleigege** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Aleigege** [comment]
> Hello, have you solved it?@Aleigege

I haven't solved it yet

**Comment by George730** [comment]
You can turn 'label[batch_edge]' into torch.LongTensor, which is similar to line 137 in fit_model.py. Try if this works.

**Comment by Aleigege** [comment]
Can you share this page of your code? thanks a lot.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "George730/E-ResGAT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月7日(星期三) 中午12:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [George730/E-ResGAT] Expected floating point type for target with class probabilities, got Long (Issue #5)





 
Closed #5 as completed.

**Comment by Aleigege** [comment]
> 你可以将 'label[batch_edge]' 变成 torch.LongTensor，这类似于 fit_model.py 中的第 137 行。试试这是否有效。

Hi, I changed it but it still runs incorrectly.

**Comment by Aleigege** [comment]
> 你好，我在运行代码的时候遇到了如下问题。我该如何解决？
> 
> .... batch: 179 loss_train: 0.0063 acc_train: 0.9980 time: 1.9977s batch: 180 loss_train: 0.0113 acc_train: 0.9943 time: 2.0366s Traceback（最近一次调试）： 文件“fit_model.py”，第180行， 适合( args) 文件“fit_model.py”，第112行，in fit acc_val, loss_val, val_output = predict_(alg, model, label, loss_fn, val) 文件“fit_model.py”，第142行，in predict_ batch_loss = loss_fn( batch_output , label[batch_edges]) 文件“/home/cetc54-5/anaconda3/envs/torchIDS/lib/python3.6/site-packages/torch/nn/modules/module.py”，第1102行，在_call_impl return forward_call ( *输入，**kwargs） 文件“/home/cetc54-5/anaconda3/envs/torchIDS/lib/python3.6/site-packages/torch/nn/modules/loss.py”，第1152行，向前 label_smoothing=self.label_smoothing) 文件“/ home/cetc54-5/anaconda3/envs/torchIDS/lib/python3.6/site-packages/torch/nn/functional.py”，第2846行，在cross_entropy 返回torch._C ._nn.cross_entropy_loss（输入，目标，权重，_Reduction.get_enum(reduction)，ignore_index，label_smoothing） RuntimeError: 具有典型率的目标的预期漂点类型，得到了长



> Hello, have you solved it?@Aleigege

Hello, did you solve it?

**Comment by junjiunian** [comment]
Not resolved yet 555555555555555..

**Comment by wlmnzf** [comment]
@Aleigege @junjiunian @heerlu  A not-so-good solution, turning line 142 ```batch_loss = loss_fn(batch_output, label[batch_edges])``` to ```batch_loss = loss_fn(torch.tensor(batch_output,dtype=torch.float32), torch.FloatTensor(torch.tensor(label[np.array(batch_edges)],dtype=torch.float32)))``` can solve the problem.

**Comment by Aleigege** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by kkkkyp** [comment]
@wlmnzf  I tried your method, but this problem occurred。
D:/PyCharm/Py_project/E-ResGAT-master/fit_model.py:148: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  batch_loss = loss_fn(torch.tensor(batch_output, dtype=torch.float32),
D:/PyCharm/Py_project/E-ResGAT-master/fit_model.py:149: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.FloatTensor(torch.tensor(label[np.array(batch_edges)], dtype=torch.float32)))
Traceback (most recent call last):
  File "D:/PyCharm/Py_project/E-ResGAT-master/fit_model.py", line 189, in <module>
    fit(args)
  File "D:/PyCharm/Py_project/E-ResGAT-master/fit_model.py", line 114, in fit
    acc_val, loss_val, val_output = predict_(alg, model, label, loss_fn, val)
  File "D:/PyCharm/Py_project/E-ResGAT-master/fit_model.py", line 149, in predict_
    torch.FloatTensor(torch.tensor(label[np.array(batch_edges)], dtype=torch.float32)))
  File "D:\Anaconda\envs\gsage\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\envs\gsage\lib\site-packages\torch\nn\modules\loss.py", line 948, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "D:\Anaconda\envs\gsage\lib\site-packages\torch\nn\functional.py", line 2422, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "D:\Anaconda\envs\gsage\lib\site-packages\torch\nn\functional.py", line 2216, in nll_loss
    .format(input.size(0), target.size(0)))
ValueError: Expected input batch_size (1) to match target batch_size (500).
**Can you help me solve it?**

**Comment by Aleigege** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
